### ISSUE TITLE
Missing sanitize_for_serialization

### ISSUE THREAD

**Issue by tanner-pm** [mParticle/mparticle-python-sdk#2]
Think we may be missing sanitize_for_serialization here https://github.com/mParticle/mparticle-python-sdk/blob/master/mparticle/api_client.py#L123

header_params = ApiClient.  (header_params)

**Comment by samdozor** [comment]
Hey @tanner-pm - this should be fixed in 0.9.5 which is available on pip. Sorry about that!

**Comment by tanner-pm** [comment]
@samdozor Still seeing the same issue there.

![image](https://cloud.githubusercontent.com/assets/15950574/21082677/1f899818-bf95-11e6-9a0b-c021e48fe591.png)

**Comment by samdozor** [comment]
hey @tanner-pm just released 0.9.6 - should be [all set now](https://github.com/mParticle/mparticle-python-sdk/commit/27dee9f385ae343791a87f0e69bd41a0533decd9).
